### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by kurtmc**
This pull request has a few changes that fit my use case better.
- First I fixed the moviedb scraper.
- I like to have the year in the filename so I added an option to that.
- And finally an option for moving, it's much faster to move the files.

### CODE REVIEW

**Comment by kurtmc** [comment]
Actually don't merge this just yet, I need to fix up the move logic, it's not renaming files correctly.

**Comment by Celedhrim** [comment]
Hi,

Thx for your ideas.

Ok for not merging now :)

**Comment by kurtmc** [comment]
I've fixed up the logic now, so it's working how I like.

Could you please merge this?

Thanks!

**Comment by Celedhrim** [comment]
Thx !

I will add $conf["move_files"] and $conf["year_in_filename"] in the default config file generation and $conf["move_files"] in the readme

**Pull request merged**
